### ISSUE TITLE
Requests based on feedback from the Fort Collins release

### ISSUE THREAD

**Issue by fattedad** [mydomino/energyfuture-web#308]
- [x] Change URLs from IDs to Names (#281)
- [x] Set City Page as the default entry page for new Fort Collins visitors (#302)
- [x] Minimize the number of authentication triggers (#303)
- [ ] Revisit "All Guides" and "My Impact" selection state (#304)
- [ ] City Page cleanup (#305) 
- [ ] Return to City Page (#306)
- [x] Send harvested email addresses to MailChimp for email campaigns (#307)
