### ISSUE TITLE
Outstanding Items

### ISSUE THREAD

**Issue by jhubert** [mydomino/energyfuture-web#97]
###### Kitty
- [ ] Manually cleanup and re-score the impact points based on the RMI doc (#108)
- [ ] Make product reviews clickable to open the reviews section on Amazon (#103)
- [ ] Add Good/Better/Best labels to products in the Amazon module (#111)
- [ ] Fix the Amazon product title styles as they broke after adding the Carousel
- [ ] Open all external links in a new tab e.g. ZipCar in "Car Sharing" (#101) 
###### Jeremy
- [ ] Google spreadsheet for admin signups (#112)
- [ ] Set up production and dev instances (#100)
###### Jithu
- [ ] Guide sorting (#109)
###### Jithu
- [ ] Questionnaire (#51)
- [ ] Space heating: need to show HomeAdvisor option (#110)
###### Kitty
- [ ] Center align radio button section in bike-on (#102)
- [ ] Fine tune map tips/markers display (#104)
- [ ] Show address info in the PlugShare map (#105)
###### Jeremy
- [ ] Image hosting (#107)
- [ ] Remaining login triggers (#50)
###### Natasha
- [ ] Metrics tracking (#28)
#### Ongoing for all
- [ ] Bug fixes (https://projects.invisionapp.com/d/#/projects/2296281/comments)
- [ ] Incorporate feedback from Carson (#123)
#### Week of Dec 8
- [ ] Put together HTML page for About Us and Contact Us. Awaiting copy from the content team.
- [ ] Admin panel (#18)
- [ ] Harvesting emails (#106)
